### ISSUE TITLE
Ревью по проекту

### ISSUE THREAD

**Issue by DramatikMan** [v-buchkov/hse_volatility_project#16]
- [x] В [requirements.txt](https://github.com/v-buchkov/hse_volatility_project/blob/main/requirements.txt) не указаны версии зависимостей. Это нужно для стабильной воспроизводимости вашей логики. В идеале лучше использовать менеджер среды, поддерживающей lock зависимостей по хэшу дистрибутива (например [Poetry](https://python-poetry.org/) или [PDM](https://pdm.fming.dev/latest/))
- [x] Хранить данные и артефакты ([раз](https://github.com/v-buchkov/hse_volatility_project/tree/main/data), [два](https://github.com/v-buchkov/hse_volatility_project/tree/main/catboost_info), [три](https://github.com/v-buchkov/hse_volatility_project/tree/main/output)) в контроле версией исходного кода не следует. Можно использовать файловые хранилища с версионированием и получать содержимое в рантайме через запросы, или подключить базу данных
- [x] Конфигурационные константы, особенно связанные в файловыми путями ([раз](https://github.com/v-buchkov/hse_volatility_project/blob/main/main.py#L9), [два](https://github.com/v-buchkov/hse_volatility_project/blob/main/static_data.py#L2)), лучше выносить в переменные окружения

**Comment by v-buchkov** [comment]
...

**Comment by v-buchkov** [comment]
fixed in https://github.com/v-buchkov/hse_volatility_project/pull/17
